import cv2
import os

# === YOLO SETTINGS ===
YOLO_INPUT_SIZE = 800
MODEL_ARCHITECTURE = "yolo11s-seg.pt"
MODEL_ARCHITECTURE_NAME = MODEL_ARCHITECTURE[:-3]
MODEL_NAME = f"{MODEL_ARCHITECTURE_NAME}_frame_detector3"

# === YOLO TEST SETTINGS ===
CONFIDENCE_THRESHOLD = 0.5
IOU_THRESHOLD = 0.65

# === CHARUCO BOARD SETTINGS ===
CHARUCOBOARD_ROWCOUNT = 5
CHARUCOBOARD_COLCOUNT = 5
SQUARE_LENGTH = 0.04  # 40 mm in meters
MARKER_LENGTH = 0.03  # 30 mm in meters
ARUCO_DICT_ID = cv2.aruco.DICT_6X6_250
ARUCO_DICT = cv2.aruco.getPredefinedDictionary(ARUCO_DICT_ID)

# === REQUIREMENTS ===
MIN_MARKERS_PER_IMAGE = 6
MIN_CORNERS_PER_IMAGE = 6

# === DETECTOR PARAMETER VALUES ===
ADAPTIVE_THRESH_WIN_SIZE_MIN = 3
ADAPTIVE_THRESH_WIN_SIZE_MAX = 23
ADAPTIVE_THRESH_WIN_SIZE_STEP = 10
MIN_MARKER_PERIMETER_RATE = 0.01
MAX_MARKER_PERIMETER_RATE = 2.0
CORNER_REFINEMENT_METHOD = cv2.aruco.CORNER_REFINE_SUBPIX

# === OUTPUT SETTINGS ===
TRAINING_OUTPUT_DIR = "yolo_training_output"

# === DATASETS ===
DATASETS_BASE = os.path.join("datasets", "testing_images")
NIGHT_TIME_IMAGES_DIR_PATH = os.path.join(DATASETS_BASE, "night_time")
BIG_WINDOWS_DIR_PATH = os.path.join(DATASETS_BASE, "big_windows")
SUPER_TESTER = os.path.join(DATASETS_BASE, "super_tester")
