spring:
  rsocket:
    server:
      transport: tcp
      port: 7001
      keep-alive:
        interval: 20000
        timeout: 90000
      data-mime-type: application/json
      metadata-mime-type: message/x.rsocket.composite-metadata.v0
  codec:
    max-in-memory-size: 64MB

docai:
  python:
    base-url: http://localhost:8000
    parse-path: /process_pdf/
    connect-timeout-ms: 5000
    read-timeout-ms: 90000
